"""Initial migration

Revision ID: 03fd3a7c24f0
Revises: 
Create Date: 2026-01-02 12:11:29.517938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fd3a7c24f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create workouts table
    op.create_table('workouts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('workout_type', sa.String(length=100), nullable=False),
        sa.Column('workout_description', sa.Text(), nullable=True),
        sa.Column('planned_duration', sa.Float(), nullable=True),
        sa.Column('planned_distance_meters', sa.Float(), nullable=True),
        sa.Column('workout_day', sa.Date(), nullable=False),
        sa.Column('coach_comments', sa.Text(), nullable=True),
        sa.Column('tss', sa.Float(), nullable=True),
        sa.Column('intensity_factor', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create workout_selections table
    op.create_table('workout_selections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workout_id', sa.Integer(), nullable=False),
        sa.Column('is_selected', sa.Boolean(), nullable=True),
        sa.Column('actual_date', sa.Date(), nullable=True),
        sa.Column('time_of_day', sa.String(length=50), nullable=True),
        sa.Column('user_notes', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create custom_workouts table
    op.create_table('custom_workouts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('workout_type', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('planned_date', sa.Date(), nullable=False),
        sa.Column('planned_duration', sa.Float(), nullable=True),
        sa.Column('time_of_day', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_workouts')
    op.drop_table('workout_selections')
    op.drop_table('workouts')
    # ### end Alembic commands ###
