"""Add TSS and distance fields to CustomWorkout

Revision ID: 18e9aa117486
Revises: 3cf5e3110701
Create Date: 2026-01-04 22:22:32.390719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e9aa117486'
down_revision: Union[str, None] = '3cf5e3110701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_workouts', sa.Column('planned_distance_meters', sa.Float(), nullable=True))
    op.add_column('custom_workouts', sa.Column('tss', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_workouts', 'tss')
    op.drop_column('custom_workouts', 'planned_distance_meters')
    # ### end Alembic commands ###
