"""add workout_location field to workout_selections and custom_workouts

Revision ID: 3cf5e3110701
Revises: c8881614f87a
Create Date: 2026-01-03 15:07:16.290340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf5e3110701'
down_revision: Union[str, None] = 'c8881614f87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_workouts', sa.Column('workout_location', sa.String(length=100), nullable=True))
    op.add_column('workout_selections', sa.Column('workout_location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_selections', 'workout_location')
    op.drop_column('custom_workouts', 'workout_location')
    # ### end Alembic commands ###
