"""Add is_custom field to workouts table

Revision ID: 4a7ad922aa06
Revises: 18e9aa117486
Create Date: 2026-01-05 16:57:47.123052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7ad922aa06'
down_revision: Union[str, None] = '18e9aa117486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_custom column with default value of False for existing rows
    op.add_column('workouts', sa.Column('is_custom', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'is_custom')
    # ### end Alembic commands ###
